prevent NoMethodError: undefined method `serialized?' for nil in tls option migration
the 'ldap_tls_options' setting does no longer exist and has therefore no format de
fined in the current code

we also fixed the value/deserialize to handle this more gracefully, but for good measure we also just pick the value directly here because that is more robust